security:
    encoders:
        Padel\AmigoBundle\Entity\User:
            algorithm: sha512
            encode_as_base64: false
            iterations: 1
#        FOS\UserBundle\Model\UserInterface: sha512
#        Padel\AmigoBundle\Entity\UserInterface: plaintext

        

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    providers:
        in_memory:
            memory:
                users:
                    admin: { password: admin, roles: 'ROLE_ADMIN' }
                    
                    
        fos_userbundle:
            id: fos_user.user_provider.username
           

    firewalls:
        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                csrf_provider: form.csrf_provider
            logout:       true
            anonymous:    true

#    access_control:
#        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
#        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
#        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
#        - { path: ^/admin/, role: ROLE_ADMIN }
